# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/sm8550-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter dm1q dm2q dm3q gts9wifi,$(TARGET_DEVICE)),)

endif
