#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/sm8550-common

PRODUCT_COPY_FILES += \
    vendor/samsung/sm8550-common/proprietary/product/etc/permissions/UimService.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/UimService.xml \
    vendor/samsung/sm8550-common/proprietary/system_ext/etc/init/tcmd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/tcmd.rc \
    vendor/samsung/sm8550-common/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/samsung/sm8550-common/proprietary/system_ext/etc/seccomp_policy/tcmd.policy:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/seccomp_policy/tcmd.policy \
    vendor/samsung/sm8550-common/proprietary/system_ext/etc/sysconfig/qti_whitelist_system_ext.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/sysconfig/qti_whitelist_system_ext.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/batching.conf:$(TARGET_COPY_OUT_VENDOR)/etc/batching.conf \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/charger_fw_fstab.qti:$(TARGET_COPY_OUT_VENDOR)/etc/charger_fw_fstab.qti \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/clstc_config_library.xml:$(TARGET_COPY_OUT_VENDOR)/etc/clstc_config_library.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/cne/mwqem.conf:$(TARGET_COPY_OUT_VENDOR)/etc/cne/mwqem.conf \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/cne/profileMwqem.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/profileMwqem.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/dax3_media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dax3_media_codecs_dolby_audio.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/default-permissions/com.qualcomm.qti.cne.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default-permissions/com.qualcomm.qti.cne.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/default_volume_tables.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default_volume_tables.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/display/DPU660.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU660.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/display/DPU670.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU670.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/display/DPU720.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU720.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/display/DPU7__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU7__.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/display/DPU820.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU820.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/display/DPU8__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU8__.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/display/DPU9__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU9__.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/display/advanced_sf_offsets.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/advanced_sf_offsets.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/display/thermallevel_to_fps.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/thermallevel_to_fps.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/eva/facedetection/model3.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facedetection/model3.dat \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/external_camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/external_camera_config.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/gnss_antenna_info.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gnss_antenna_info.conf \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/gpfspath_oem_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gpfspath_oem_config.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/gps.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gps.conf \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/android.hardware.drm-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.widevine.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/android.hardware.gnss-aidl-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-aidl-service-qti.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-strongbox-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-strongbox-service-qti.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service-qti.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/camera.unihal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camera.unihal.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/hermesd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hermesd.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/hw/init.qti.kernel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.qti.kernel.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/init.audio.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.audio.samsung.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/init.qccvendor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qccvendor.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/init.qti.media.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.media.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/init.qti.qcv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.qcv.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/init.spdaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.spdaemon.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/init.vendor.sensors.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.sensors.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/init_thermal-engine-v2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_thermal-engine-v2.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/ipa_fws.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipa_fws.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/ipacm-diag.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipacm-diag.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/loc-launcher.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/loc-launcher.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/qdcmss.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qdcmss.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/qmipriod.debug.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qmipriod.debug.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/qmipriod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qmipriod.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/qms.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qms.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/qseecomd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qseecomd.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/qwesd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qwesd.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/secaudiohalaidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/secaudiohalaidl.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/shsusrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/shsusrd.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/ssgtzd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ssgtzd.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/trusteduilistener.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trusteduilistener.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/vendor.qti.adsprpc-guestos-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-guestos-service.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/vendor.qti.cdsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.cdsprpc-service.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/vendor.qti.diag.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.diag.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/vendor.qti.hardware.dsp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.dsp@1.0-service.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/vendor.qti.hardware.trustedui@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.trustedui@1.0-service-qti.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/vendor.qti.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.media.c2@1.0-service.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/vendor.qti.media.c2audio@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.media.c2audio@1.0-service.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/vendor.samsung.hardware.camera.provider-service_64.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.camera.provider-service_64.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/vendor.samsung.hardware.thermal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.thermal@1.0-service.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/vendor.sensors.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.qti.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/init/vendor.sensors.sscrpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.sscrpcd.rc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/izat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/izat.conf \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/lowi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lowi.conf \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/media_codecs_kalama.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_kalama.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/media_codecs_performance_kalama.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_kalama.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/media_kalama/video_system_specs.json:$(TARGET_COPY_OUT_VENDOR)/etc/media_kalama/video_system_specs.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/media_profiles.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/media_profiles_kalama.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_kalama.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/models/acd/event.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/event.eai \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/models/acd/music.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/music.eai \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/models/acd/speech.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/speech.eai \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/msm_irqbalance.conf:$(TARGET_COPY_OUT_VENDOR)/etc/msm_irqbalance.conf \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/permissions/vendor.android.hardware.camera.preview-dis.back.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor.android.hardware.camera.preview-dis.back.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/portrait_data/LF_segmenter/LF_segmenter_cnn.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/portrait_data/LF_segmenter/LF_segmenter_cnn.dlc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/portrait_data/LF_segmenter/LF_segmenter_cnn.info:$(TARGET_COPY_OUT_VENDOR)/etc/portrait_data/LF_segmenter/LF_segmenter_cnn.info \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/portrait_data/SRIB_HumanSegVideo_INT8_V102_sm8550_snpe2213_vendor.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/portrait_data/SRIB_HumanSegVideo_INT8_V102_sm8550_snpe2213_vendor.dlc \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/portrait_data/single_bokeh_feature_vendor.json:$(TARGET_COPY_OUT_VENDOR)/etc/portrait_data/single_bokeh_feature_vendor.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sec_audio_volume_curve.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sec_audio_volume_curve.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/seccomp_policy/atfwd@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/atfwd@2.0.policy \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.base-arm64.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.base-arm64.policy \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.ext-arm64.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.ext-arm64.policy \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-base.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-base.policy \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-xtra-daemon.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-xtra-daemon.policy \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-xtwifi-client.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-xtwifi-client.policy \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/seccomp_policy/qms.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qms.policy \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/seccomp_policy/qti-systemd.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qti-systemd.policy \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/seccomp_policy/qwesd@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qwesd@2.0.policy \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/seccomp_policy/vendor.qti.hardware.dsp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/vendor.qti.hardware.dsp.policy \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/secnvm/k250a_47000301_0.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_47000301_0.img \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/secnvm/k250a_47000304_c.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_47000304_c.img \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/secnvm/k250a_47000306_1.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_47000306_1.img \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/akmlib.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/akmlib.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/kailua_dynamic_sensors_template.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_dynamic_sensors_template.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_hdk_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_hdk_dae.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/kailua_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_power_0.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/kailua_qsh_ble_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_qsh_ble_0.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/qsh_ble.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_ble.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_direct_channel.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_direct_channel.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_flip_state.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_flip_state.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_fmv_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv_legacy.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_offbody_detect_phone.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_offbody_detect_phone.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/config/sns_transport_ppe.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_transport_ppe.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/snapdragon_color_libs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/snapdragon_color_libs_config.xml \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/ssg/ta_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/ta_config.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/ssg/tz_whitelist.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/tz_whitelist.json \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/wifi/indoorchannel.info:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/indoorchannel.info \
    vendor/samsung/sm8550-common/proprietary/vendor/etc/xtwifi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/xtwifi.conf \
    vendor/samsung/sm8550-common/proprietary/vendor/firmware/ss_dsi_panel_PBA_BOOTING_FHD.dat:$(TARGET_COPY_OUT_VENDOR)/firmware/ss_dsi_panel_PBA_BOOTING_FHD.dat \
    vendor/samsung/sm8550-common/proprietary/vendor/firmware/wlan-connection-roaming-backup.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan-connection-roaming-backup.ini \
    vendor/samsung/sm8550-common/proprietary/vendor/firmware/wlan-connection-roaming.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan-connection-roaming.ini \
    vendor/samsung/sm8550-common/proprietary/vendor/gpu/kbc/sequence_manifest.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/sequence_manifest.bin \
    vendor/samsung/sm8550-common/proprietary/vendor/gpu/kbc/unified_kbcs_64.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/unified_kbcs_64.bin \
    vendor/samsung/sm8550-common/proprietary/vendor/gpu/kbc/unified_ksqs.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/unified_ksqs.bin \
    vendor/samsung/sm8550-common/proprietary/vendor/lib64/AIAwbModel_v2.2.tflite:$(TARGET_COPY_OUT_VENDOR)/lib64/AIAwbModel_v2.2.tflite \
    vendor/samsung/sm8550-common/proprietary/vendor/lib64/camera/f_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/f_dual_calibration.bin \
    vendor/samsung/sm8550-common/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/samsung/sm8550-common/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/samsung/sm8550-common/proprietary/vendor/lib64/camera/fdconfigsecure.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigsecure.bin \
    vendor/samsung/sm8550-common/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/samsung/sm8550-common/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin

PRODUCT_PACKAGES += \
    vendor.qti.diaghal-V1-ndk \
    cdsp_face \
    com.qti.qseeaon \
    com.qti.qseeutils \
    com.qualcomm.qti.dpm.api@1.0 \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libVkLayer_ADRENO_qprofiler \
    libq3dtools_adreno \
    libq3dtools_esx \
    android.hardware.gnss-aidl-impl-qti \
    camera.unihal.default \
    gatekeeper.mdfpp \
    libsecaudiohal_aidl \
    sensors.dynamic_sensor_hal \
    vendor.qti.hardware.capabilityconfigstore@1.0-impl \
    vendor.qti.hardware.qccvndhal@1.0-impl \
    vendor.qti.hardware.qseecom@1.0-impl \
    vulkan.adreno \
    libAFSegmenter_v1.camera.samsung \
    libAIHighRes_interface \
    libAlacSwDec \
    libApeSwDec \
    libBlurDetectionDeepLearning.camera.samsung \
    libCB \
    libDLInterface.camera.samsung \
    libDeviceInfoProvider \
    libEventFinder.camera.samsung \
    libEvrcSwCodec \
    libFace3DTA \
    libFace3D_hlos \
    libFace_Landmark_API.camera.samsung \
    libFastUWDistortionCorrection.camera.samsung \
    libFlacSwDec \
    libGPMTEEC_vendor \
    libGPQTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libHDRVerifier_v1.camera.samsung \
    libHandGesture.camera.samsung \
    libHprFace_GAE_api.camera.samsung \
    libHprVisualEffect \
    libHpr_RecGAE_cvFeature_v1.0.camera.samsung \
    libHumanSegVideoModel_Vendor \
    libLightObjectDetector_v1.camera.samsung \
    libLocalTM_capture_core.camera.samsung \
    libLocalTM_wrapper.camera.samsung \
    libMoireDetection.camera.samsung \
    libMoireDetectionWrapper.camera.samsung \
    libMoireDetector.uniplugin@1.0 \
    libMoonVerifier_v1.camera.samsung \
    libObjectDetector_v1.camera.samsung \
    libOpenCL \
    libOpenCv.camera.samsung \
    libPanDetector \
    libPeripheralStateUtils \
    libPersonal_capture.camera.samsung \
    libPersonal_core.camera.samsung \
    libPetDetector_interface \
    libQ6MSFR_manager_stub \
    libQSEEComAPI \
    libQTEEConnector_vendor \
    libQcelp13SwCodec \
    libRelighting_API.camera.samsung \
    libSNPE \
    libSRIB_ARVL_HAP.camera.samsung \
    libSceneDetector_v1.camera.samsung \
    libSecJpegEncoder.uniplugin@1.0 \
    libSnpeCpu \
    libSnpeGpu \
    libSnpeHtpV73Stub \
    libTouchInputVM \
    libTrustedInput \
    libTrustedInputTZ \
    libTrustedInputUtils \
    libTrustedUI \
    libTrustedUITZ \
    libTrustedUIVM \
    libUniPluginUtils \
    libVideoSuperNight_interface.uniplugin@1.0 \
    lib_SoundAlive_3DPosition_ver202 \
    lib_SoundAlive_AlbumArt_ver105 \
    lib_SoundBooster_ver1100 \
    lib_profiler \
    libadm \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libai_denoiser_interface \
    libaidenoiser \
    libaidenoiserv2 \
    libaivideocentral.arcsoft \
    libarcsoft_deflicker_native \
    libarcsoft_dualcam_portraitlighting_preview \
    libarcsoft_object_tracking \
    libarcsoft_video_super_night \
    libatccore \
    libaudio_log_utils \
    libauto_framing_arcsoft.uniplugin@1.0 \
    libautotracking_interface \
    libbacklight-calib \
    libbatching \
    libbitmlengine \
    libbitmlenginev2 \
    libbodyid.arcsoft \
    libc++_shared \
    libc2filterplugin \
    libcacertclient \
    libcamxcommonutils \
    libcamxfacialfeatures \
    libcamxfdalgo \
    libcamxfdengine \
    libcamxhwnodecontext \
    libcamxifestriping \
    libcamxqsatalgo \
    libcamxsettingsmanager \
    libcamxstatscore \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libcapiv2svacnnvendor \
    libcapiv2svarnnvendor \
    libcapiv2udk7vendor \
    libcapiv2uvvendor \
    libcdfw \
    libcdfw_remote_api \
    libcdsp_default_listener \
    libcdsprpc \
    libchilog \
    libclstc_algorithm_adapter \
    libclstc_gcp_adapter \
    libclstc_tm \
    libcneapiclient \
    libcommonchiutils \
    libconfigdb \
    libcpion \
    libcv_common \
    libdataitems \
    libdiag \
    libdiagjni \
    libdigital-dimming \
    libdisp-aba \
    libdisplayqos \
    libdisplayskuutils \
    libdpps \
    libdrmfs \
    libdrmtime \
    libdsd2pcm \
    libdsi_netctrl \
    libdsmanager \
    libdsphist_qc \
    libdsutils \
    libdualcam_refocus_video \
    libegis_fp_normal_sensor_test \
    libengine_did \
    libengmode_client \
    libese-grdg \
    libeva \
    libeva_util \
    libevent_finder.uniplugin@1.0 \
    libexifa.camera.samsung \
    libface3d_dev \
    libface_landmark.arcsoft \
    libfast_uwdc.uniplugin@1.0 \
    libfastcvdsp_stub \
    libfastcvopt \
    libfeutils \
    libfloatingfeature \
    libfloatingfeature_hal \
    libfocuspeaking \
    libfocuspeaking.uniplugin@1.0 \
    libformatConverter.unifunc \
    libgame_enhance \
    libgeofencing \
    libgf_in_system_lib \
    libgnss \
    libgnsspps \
    libgps.utils \
    libgpt \
    libgpudataproducer \
    libgralloc_helper.unifunc \
    libgsl \
    libhand_interaction.uniplugin@1.0 \
    libhandgesture.arcsoft \
    libhdr10plus \
    libhdr_backlight_adapter \
    libhdr_stub \
    libhdr_tm \
    libhdradaptivecustom \
    libhdraid.gpu.arcsoft \
    libhdraid.npu.arcsoft \
    libhdrdynamic \
    libhdrdynamicootf \
    libheifcapture \
    libhermes \
    libhermes_bdbridge \
    libhermes_cred \
    libhme \
    libhwvault \
    libhypermotion_core \
    libidl \
    libimage_enhancement.arcsoft \
    libimagecodec_native.quram \
    libimgproc_sw.unifunc@common \
    libintervmipc \
    libipebpsstriping \
    libipebpsstriping170 \
    libipebpsstriping480 \
    libisphwsetting \
    libizat_client_api \
    libizat_core \
    libjnihelper \
    libjpegQtable_interface \
    libjpege \
    libjpegencoder_sw.unifunc \
    libjpegsq.media.samsung \
    libkcl \
    libkernelmanager \
    libkeymasterdeviceutils \
    libkeymasterutils \
    liblbs_core \
    liblistensoundmodel2vendor \
    libllvm-glnext \
    libllvm-qcom \
    libllvm-qgl \
    libloadalgo_stub \
    libloc_api_v02 \
    libloc_api_wds \
    libloc_base_util \
    libloc_core \
    libloc_mq_client \
    libloc_qwes_iface \
    libloc_socket \
    libloc_util \
    liblocation_api \
    liblocation_api_msg \
    liblocation_client_api \
    liblocation_integration_api \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblowi_common \
    liblowi_wifihal \
    libmaskdetection.uniplugin@1.0 \
    libmcaimegpu.samsung \
    libmctfengine_stub \
    libmdmdetect \
    libmdmimgload \
    libmdsprpc \
    libmemutils \
    libmfGhostDetection \
    libmfec \
    libminkdescriptor \
    libminksocket_vendor \
    libmm-hdcpmgr \
    libmmcamera_bestats \
    libmmcamera_cac3 \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmmcamera_pdpc \
    libmmosal_vendor \
    libmpbase \
    libmultiobject_tracker \
    libnanopb \
    libnetmgr \
    libnetmgr_common \
    libnetmgr_datapath_proxy \
    libnetmgr_sscm3 \
    libnetmgr_utils \
    libnetmgrmodemproxy \
    libnetmgrportutils \
    libnetmgrxfrmutils \
    libnlnetmgr \
    liboemcrypto \
    libopencv \
    libopencv3a \
    libopestriping \
    libops \
    libos \
    libpadm \
    libpal_net_if \
    libpantilt_detector.uniplugin@1.0 \
    libpdmapper \
    libpdnotifier \
    libperipheral_client \
    libpersonalimprinting.uniplugin@1.0 \
    libpet_detector.uniplugin@1.0 \
    libpetcamera_engine \
    libprofileparamstorage \
    libqc2audio_base \
    libqc2audio_basecodec \
    libqc2audio_core \
    libqc2audio_hooks \
    libqc2audio_platform \
    libqc2audio_swaudiocodec \
    libqc2audio_utils \
    libqc2colorconvertfilter \
    libqc2filter \
    libqcbor \
    libqcc_file_agent \
    libqcc_sdk \
    libqcci_legacy \
    libqcmaputils \
    libqcodec2_base \
    libqcodec2_basecodec \
    libqcodec2_core \
    libqcodec2_cvpfilter \
    libqcodec2_filterbase \
    libqcodec2_hooks \
    libqcodec2_imgtxrfilter \
    libqcodec2_mockfilter \
    libqcodec2_mockqc2filter \
    libqcodec2_platform \
    libqcodec2_utils \
    libqcodec2_v4l2codec \
    libqdcm-algo \
    libqdcm-json-mode-parser \
    libqdcm-mode-parser \
    libqdi \
    libqdp \
    libqdpr \
    libqisl \
    libqll \
    libqll10 \
    libqllengine \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_csvt_srvc \
    libqmi_encdec \
    libqmi_legacy \
    libqmiservices \
    libqnnengine \
    libqrtr \
    libqrtrclient \
    libqseed3 \
    libqsegnet \
    libqshcamera \
    libqsocket \
    libqtigefar \
    libqtikeymaster4 \
    librapidscorerplus \
    librcmask \
    librmengine_plus.uniplugin@1.0 \
    librpmb \
    libsamsungcamerahal \
    libsamsungcamerahalutils \
    libsamsungcamerahwl_impl \
    libsavscmn \
    libsavsvc \
    libscaler_hw.unifunc \
    libscaler_sw.unifunc \
    libscenedetector.uniplugin@1.0 \
    libscveCommon \
    libscveCommon_stub \
    libscveObjectSegmentation \
    libscveObjectSegmentation_stub \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libsdm-color \
    libsdm-colormgr-algo \
    libsdm-disp-vndapis \
    libsdmextension \
    libsdsprpc \
    libsec2imageformatfilter \
    libsecaudiocoreutils \
    libsecaudioinfo \
    libsecaudiolevel \
    libsecfr_engine \
    libsecfr_model \
    libsecnativefeature \
    libsecril-client_vendor \
    libsecureui_svcsock \
    libsegmentationeffect.uniplugin@1.0 \
    libsegmentationeffect_capture.uniplugin@1.0 \
    libsemnativecarrierfeature \
    libsensorlistener \
    libsensorndkbridge \
    libsensorslog \
    libsfeShiftExtrapolation \
    libshctrl \
    libshotsuggestion \
    libshotsuggestion_engines \
    libshsc \
    libsi \
    libsimba.media.samsung \
    libskeymint10device \
    libskeymint_cli \
    libsmemlog \
    libsnap_compute \
    libsnap_compute_secure \
    libsnap_compute_wrapper \
    libsnap_compute_wrapper_secure \
    libsnap_qnn \
    libsnap_vndk \
    libsnap_vndk_secure \
    libsnapdragoncolor-manager \
    libsnapdragoncolor-qdcm \
    libsnaplite_native \
    libsnaplite_native_secure \
    libsnaplite_wrapper \
    libsnaplite_wrapper_secure \
    libsnapmw \
    libsnpe_dsp_domains_v3 \
    libsnpe_wrapper \
    libsns_api \
    libsns_device_mode_stub \
    libsns_direct_channel_stub \
    libsns_dynamic_loader_stub \
    libsns_registry_skel \
    libsns_remote_proc_state_stub \
    libsnsapi \
    libsnsdiaglog \
    libsnsutils \
    libsocial_image_enhancement.uniplugin@1.0 \
    libspatializerparamstorage \
    libspcom \
    libspeakercalibration \
    libspl \
    libsrib_CNNInterface.camera.samsung \
    libsrib_humanaware_engine.camera.samsung \
    libssc \
    libssc_default_listener \
    libssd \
    libssengine.uniplugin@1.0 \
    libstagefright_foundation_vendor \
    libstreamparser \
    libswregistrationalgo \
    libsynaFpSensorTestNwd \
    libsynergy_loc_api \
    libsynx \
    libsys_info_cache \
    libsysmon_cdsp_skel \
    libsystem_health_mon \
    libtensorflowLite.singletake.camera.samsung \
    libtensorflowlite.camera.samsung \
    libtestutils \
    libtfestriping \
    libtflitecore \
    libthermalclient \
    libthreadutils \
    libtime_genoff \
    libtinyxml2_1 \
    libtrustedapploader \
    libtswrappercommon \
    libubifocus \
    libuniplugin \
    libvdis_core \
    libvideobeauty.arcsoft \
    libvideobeauty.uniplugin@1.0 \
    libvideobeauty_capture.uniplugin@1.0 \
    libvideobeauty_interface \
    libvideoml \
    libvideotxr \
    libvideoutils \
    libvkmanager_vendor \
    libvmfilexfer \
    libvmmem \
    libwvaidl \
    libxml \
    libxtadapter \
    libzoomroi.samsung \
    libdrmclearkeyplugin \
    qti.video.utils.videobufferlayout \
    libQnnHtp \
    libQnnHtpV73Stub \
    libQnnSystem \
    libasphere \
    libaudioeffectoffload \
    libmyspace \
    libquasar \
    libshoebox \
    unihal_android \
    unihal_cutils \
    unihal_entry \
    unihal_filter_unit \
    unihal_main \
    unihal_scenario \
    unihal_uniplugin@1.0 \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.color@1.3 \
    vendor.display.color@1.4 \
    vendor.display.color@1.5 \
    vendor.display.color@1.6 \
    vendor.display.color@1.7 \
    vendor.display.postproc@1.0 \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.factory@2.2 \
    vendor.qti.data.factory@2.3 \
    vendor.qti.data.factory@2.4 \
    vendor.qti.data.factory@2.5 \
    vendor.qti.data.factory@2.6 \
    vendor.qti.data.factory@2.7 \
    vendor.qti.data.mwqem@1.0 \
    vendor.qti.data.slm@1.0 \
    vendor.qti.diaghal@1.0_vendor \
    vendor.qti.esepowermanager@1.0 \
    vendor.qti.gnss-V4-ndk \
    vendor.qti.gnss-service \
    vendor.qti.hardware.cacert@1.0 \
    vendor.qti.hardware.camera.aon-service-impl \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.1 \
    vendor.qti.hardware.data.cne.internal.server@1.2 \
    vendor.qti.hardware.data.cne.internal.server@1.3 \
    vendor.qti.hardware.data.connectionfactory-V1-ndk \
    vendor.qti.hardware.data.dataactivity-V1-ndk \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.dynamicdds@1.1 \
    vendor.qti.hardware.data.flow@1.0 \
    vendor.qti.hardware.data.flow@1.1 \
    vendor.qti.hardware.data.ka-V1-ndk \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.lce@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.dsp@1.0 \
    vendor.qti.hardware.mwqemadapter@1.0 \
    vendor.qti.hardware.pal@1.0-impl \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.qccsyshal@1.1 \
    vendor.qti.hardware.qccsyshal@1.2 \
    vendor.qti.hardware.qccvndhal@1.0-halimpl \
    vendor.qti.hardware.qccvndhal@1.0 \
    vendor.qti.hardware.qdutils_disp@1.0 \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.radio.atcmdfwd-V1-ndk \
    vendor.qti.hardware.radio.atcmdfwd@1.0 \
    vendor.qti.hardware.slmadapter@1.0 \
    vendor.qti.hardware.trustedui@1.0 \
    vendor.qti.hardware.trustedui@1.1 \
    vendor.qti.hardware.trustedui@1.2 \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.latency@2.0 \
    vendor.qti.latency@2.1 \
    vendor.qti.latency@2.2 \
    vendor.samsung.hardware.audio-V1-ndk \
    vendor.samsung.hardware.audio@1.0 \
    vendor.samsung.hardware.biometrics.fingerprint-V1-ndk \
    vendor.samsung.hardware.camera.device-V1-ndk \
    vendor.samsung.hardware.camera.provider-V1-ndk \
    vendor.samsung.hardware.gnss-V2-ndk_platform \
    vendor.samsung.hardware.hyper-V2-ndk \
    vendor.samsung.hardware.keymint-V2-ndk \
    vendor.samsung.hardware.security.drk-V1-ndk \
    vendor.samsung.hardware.security.drk@2.0 \
    vendor.samsung.hardware.security.hermes-V1-ndk \
    vendor.samsung.hardware.thermal@1.0 \
    bm3a68v08s11n29 \
    bm3a68v08s11n30 \
    bm3a68v08s11n35 \
    bm3a68v08s11n36 \
    bm3a68v08s11n37 \
    bm3a68v08s11n38 \
    bm3a68v08s11n39 \
    bm3a68v08s11n40 \
    bm3a68v08s11n46 \
    bm3a68v08s11n47 \
    bm3a68v08s11n48 \
    bm3a68v08s11n49 \
    bm3a68v08s11n52 \
    bm3a68v08s11n53 \
    bm3a73v08s11n02 \
    bm3a73v08s11n03 \
    bm3a73v08s11n04 \
    bm3a73v08s11n06 \
    bm3a73v08s11n07 \
    bm3a73v08s11n08 \
    bm3a73v08s11n09 \
    bm3a73v08s11n12 \
    bm3a73v08s11n13 \
    bm3a73v08s11n14 \
    bm3a73v08s11n15 \
    bm3a73v08s11n16 \
    bm3a73v08s11n17 \
    bm3a73v08s11n18 \
    bm3a73v08s11n19 \
    bm3a73v08s11n20 \
    bm3a73v08s11n21 \
    bm3a73v08s11n22 \
    bm3a73v08s11n23 \
    bm3a73v08s11n24 \
    bm3a73v08s11n25 \
    bm3a73v08s11n26 \
    bm3a73v08s11n27 \
    bm3a73v08s11n28 \
    bm3a73v08s11n41 \
    bm3a73v08s11n42 \
    bm3a73v08s11n43 \
    bm3a73v08s11n44 \
    bm3a73v08s11n45 \
    bm3a73v08s11n50 \
    bm3a73v08s11n51 \
    libQ6MSFR_manager_skel \
    libSnpeHtpV73Skel \
    libadsp_jpege_skel \
    libapn_dsp_skel \
    libbitml_nsp_skel \
    libbitml_nsp_v2_skel \
    libdspCV_skel \
    libdsp_streamer_binning \
    libdsphist_qc_skel \
    libdspmc_qc_skel \
    libevadsp_3_0 \
    libfastcvadsp \
    libfastcvdsp_skel \
    libhdr_skel \
    libmctfengine_skel \
    libmobilenet_dsp_frc \
    libmobilenet_dsp_frc_networks \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    libvpt_action_recognition \
    libQnnHtpV73Skel \
    libdiag_system \
    libmmosal \
    libmmparser_lite \
    vendor.qti.diaghal@1.0 \
    CACertService \
    TimeService \
    HotwordEnrollmentOKGoogleEx4HEXAGON \
    HotwordEnrollmentXGoogleEx4HEXAGON \
    uimservicelibrary \
    com.android.hotwordenrollment.common.util \
    vendor.qti.ims.connection-V1.0-java \
    vendor.qti.ims.factory-V2.0-java \
    vendor.qti.ims.factory-V2.1-java \
    vendor.qti.ims.factory-V2.2-java \
    vendor.qti.ims.rcssip-V1.0-java \
    vendor.qti.ims.rcssip-V1.1-java \
    vendor.qti.ims.rcssip-V1.2-java \
    vendor.qti.ims.rcsuce-V1.0-java \
    vendor.qti.ims.rcsuce-V1.1-java \
    vendor.qti.ims.rcsuce-V1.2-java \
    android.hardware.gnss-aidl-service-qti.xml \
    android.hardware.security.keymint-service-qti.xml \
    c2_manifest_vendor_audio.xml \
    iweaver_v1_manifest.xml \
    manifest_android.hardware.drm-service.widevine.xml \
    qms-saidl.xml \
    sec_c2_manifest_default0_1_0.xml \
    secaudiohalaidl_manifest.xml \
    vendor.qti.camera.aon-impl-1.3.xml \
    vendor.qti.camera.postproc-impl.xml \
    vendor.qti.diag.hal.service.xml \
    vendor.qti.gnss-service.xml \
    vendor.samsung.hardware.camera.provider-service.xml \
    vendor.samsung.hardware.thermal@1.0-manifest.xml \
    ATFWD-daemon \
    adpl \
    adsprpcd \
    cdsprpcd \
    cnss-daemon \
    diag-router \
    dspservice \
    hermesd \
    android.hardware.drm-service.widevine \
    android.hardware.gnss-aidl-service-qti \
    android.hardware.keymaster@4.0-strongbox-service-qti \
    android.hardware.security.keymint-service-qti \
    secaudiohalaidl \
    vendor.qti.hardware.capabilityconfigstore@1.0-service \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.trustedui@1.0-service-qti \
    vendor.qti.media.c2@1.0-service \
    vendor.qti.media.c2audio@1.0-service \
    vendor.samsung.hardware.camera.provider-service_64 \
    init.kernel.post_boot-kalama \
    init.kernel.post_boot \
    init.qcom.class_core \
    init.qcom.sensors \
    init.qti.kernel \
    init.qti.media \
    init.qti.qcv \
    init.qti.write \
    ipacm-diag \
    irsc_util \
    ks \
    loadalgo \
    loc_launcher \
    lowi-server \
    mdm_helper \
    mdm_helper_proxy \
    netmgrd \
    pd-mapper \
    pktlogconf \
    pm-proxy \
    pm-service \
    ppd \
    qcc-vendor \
    qdcmss \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    qwesd \
    rmt_storage \
    sec_nvm \
    sensors.qti \
    shsusrd \
    spdaemon \
    sscrpcd \
    ssgtzd \
    ssr_diag \
    ssr_setup \
    subsystem_ramdump \
    system_dlkm_modprobe \
    tftp_server \
    thermal-engine-v2 \
    time_daemon \
    trusteduilistener \
    vendor_modprobe \
    xtra-daemon

PRODUCT_PACKAGES += \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so
